sonar.projectKey=BookStore
sonar.projectName=bookStore
sonar.host.url=http://localhost:9000
sonar.token=sqa_9675e5d4e0fc37bc768811f0dddf2a538894b566
sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

sonar.exclusions=**src/pages/**,**/node_modules/**,**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts,src/main.tsx,src/App.tsx,src/services/apiConnector.ts,src/setupTests.ts,src/api/bookApi.ts,src/api/userApi.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
